#!/bin/bash

### banner
#
### Banner with color ###
# by rern

usage() {
echo -e "
\e[36m---------------------------------------------------------\e[0m
usage: banner [OPTION] "STRING"
\e[36m---------------------------------------------------------\e[0m
OPTION:
-c N    - color code (256 colors mode)
-f file - save to file (to be used as 'cat output')
-m      - used as 'motd' in terminal login screen
-r      - restore original 'motd'

STRING  - all characters will be converted to uppercase
\e[36m---------------------------------------------------------\e[0m
"
exit
}
[[ $# == 0 ]] && usage

A=(
'  #  '
' # # '
'#   #'
'#####'
'#   #'
)
B=(
'#### '
'#   #'
'#### '
'#   #'
'#### '
)
C=(
' ### '
'#   #'
'#    '
'#   #'
' ### '
)
D=(
'#### '
'#   #'
'#   #'
'#   #'
'#### '
)
E=(
'#####'
'#    '
'###  '
'#    '
'#####'
)
F=(
'#####'
'#    '
'###  '
'#    '
'#    '
)
G=(
' ####'
'#    '
'#  ##'
'#   #'
' ####'
)
H=(
'#   #'
'#   #'
'#####'
'#   #'
'#   #'
)
I=(
' ### '
'  #  '
'  #  '
'  #  '
' ### '
)
J=(
'  ###'
'    #'
'    #'
'#   #'
' ### '
)
K=(
'#   #'
'#  # '
'###  '
'#  # '
'#   #'
)
L=(
'#    '
'#    '
'#    '
'#    '
'#####'
)
M=(
'#   #'
'## ##'
'# # #'
'#   #'
'#   #'
)
N=(
'#   #'
'##  #'
'# # #'
'#  ##'
'#   #'
)
O=(
' ### '
'#   #'
'#   #'
'#   #'
' ### '
)
P=(
'#### '
'#   #'
'#### '
'#    '
'#    '
)
Q=(
' ### '
'#   #'
'# # #'
'#  # '
' ## #'
)
R=(
'#### '
'#   #'
'#### '
'#  # '
'#   #'
)
S=(
' ####'
'#    '
' ### '
'    #'
'#### '
)
T=(
'#####'
'  #  '
'  #  '
'  #  '
'  #  '
)
U=(
'#   #'
'#   #'
'#   #'
'#   #'
' ### '
)
V=(
'#   #'
'#   #'
'#   #'
' # # '
'  #  '
)
W=(
'#   #'
'#   #'
'# # #'
'## ##'
'#   #'
)
X=(
'#   #'
' # # '
'  #  '
' # # '
'#   #'
)
Y=(
'#   #'
' # # '
'  #  '
'  #  '
'  #  '
)
Z=(
'#####'
'   # '
'  #  '
' #   '
'#####'
)
n1=(
'  #  '
' ##  '
'  #  '
'  #  '
' ### '
)
n2=(
' ### '
'#   #'
'   # '
' #   '
'#####'
)
n3=(
' ### '
'#   #'
'   # '
'#   #'
' ### '
)
n4=(
'   # '
'  ## '
' # # '
'#####'
'   # '
)
n5=(
'#### '
'#    '
'#### '
'    #'
'#### '
)
n6=(
' ### '
'#    '
'#####'
'#   #'
' ### '
)
n7=(
'#####'
'   # '
'  #  '
' #   '
' #   '
)
n8=(
' ### '
'#   #'
' ### '
'#   #'
' ### '
)
n9=(
' ### '
'#   #'
' ####'
'    #'
' ### '
)
space=(
'     '
'     '
'     '
'     '
'     '
)
slash=(
'    #'
'   # '
'  #  '
' #   '
'#    '
)
dash=(
'     '
'     '
'#####'
'     '
'     '
)
plus=(
'     '
'  #  '
'#####'
'  #  '
'     '
)
asterisk=(
'     '
'  #  '
'#####'
' # # '
'     '
)
dot=(
'     '
'     '
'     '
' ### '
' ### '
)
comma=(
'     '
'     '
'     '
' ##  '
'  #  '
)
quote=(
'  #  '
'  #  '
'     '
'     '
'     '
)
dblquote=(
' # # '
' # # '
'     '
'     '
'     '
)
parenl=(
'  #  '
' #   '
' #   '
' #   '
'  #  '
)
parenr=(
'  #  '
'   # '
'   # '
'   # '
'  #  '
)
quest=(
' ### '
'#   #'
'  ## '
'     '
'  #  '
)
exclaim=(
'  #  '
'  #  '
'  #  '
'     '
'  #  '
)
hash=(
' #  # '
'######'
' #  # '
'######'
' #  # '
)

colorl=''
colorr=''
file=''
motd=''
while :; do
	case $1 in
		-c) colorl="\e[38;5;${2}m"
			colorr="\e[0m"
			shift;;
		-f) file=$2
			shift;;
		-m) motd=1;;
		-r) if [[ ! -f /etc/motd.banner ]]; then
				echo -e "\nNo custom 'motd' banner found.\n"
				exit
			fi
			rm -f /etc/motd.banner
			rm -f /etc/profile.d/motd.sh
			sed -i '\|cat /etc/banner|d' /etc/profile
			[[ -e /etc/motd.original ]] && mv /etc/motd{.original,}
			cat /etc/motd
			echo -e "Relogin to see this original 'mtod'.\n"
			exit
			;;
		-h|-\?|--help) usage;;
		-?*) echo -e "\nUnknown option: $1"
			usage;;
		*) break
	esac
	shift
done

string=${@^^}
# loop string to array
for (( i=0 ; i < ${#string} ; i++ )); do
	# extract each character
	char=${string:i:1}
	# numbers and symbols substitue to use as variable names
	case "$char" in
		[1-9]) char="n$char";;
		0) char='O';;
		' ') char='space';;
		'/') char='slash';;
		'-') char='dash';;
		'+') char='plus';;
		'*') char='asterisk';;
		'.') char='dot';;
		',') char='comma';;
		"'") char='quote';;
		'"') char='dblquote';;
		'?') char='quest';;
		'!') char='exclaim';;
		'#') char='hash';;
		'(') char='parenl';;
		')') char='parenr';;
		[^A-Z,a-z]) char='space';;
	esac
	# array - name of each line of each character: ar0=(A[0], B[0], C[0], ..)
	ar0[i]=${char}[0]
	ar1[i]=${char}[1]
	ar2[i]=${char}[2]
	ar3[i]=${char}[3]
	ar4[i]=${char}[4]
done

# line - compose with '!'indirect variables to array: li0=" $A[0] $B[0] $C[0] ... "
li0=" " li1=" "; li2=" "; li3=" "; li4=" "
for (( i=0 ; i < ${#string} ; i++ )); do
	li0=$li0"${!ar0[i]} "
	li1=$li1"${!ar1[i]} "
	li2=$li2"${!ar2[i]} "
	li3=$li3"${!ar3[i]} "
	li4=$li4"${!ar4[i]} "
done

# output
banner="$colorl
$li0
$li1
$li2
$li3
$li4
$colorr"

echo -e "$banner"

# save to file
if [[ $file ]]; then
	echo -e "$banner" > $file
	echo -e "\ncat $file \e[38;5;240m# to display the banner\e[0m\n"
fi

# modify 'motd'
if [[ $motd ]]; then
	echo -e "$banner" > /etc/motd.banner
	if [[ -d /etc/profile.d ]]; then
		echo -e '#!/bin/bash\ncat /etc/motd.banner' > /etc/profile.d/motd.sh
		chmod +x /etc/profile.d/motd.sh
	else
		echo 'cat /etc/motd.banner' >> /etc/profile
	fi
	mv /etc/motd{,.original}
	echo -e "Relogin to see new 'mtod' banner.\n"
fi
